In [1]:
import pandas as pd
import torch
import numpy as np
import matplotlib.pyplot as plt

In [2]:
scalar=torch.tensor(6)

In [3]:
scalar


tensor(6)

In [4]:
# vector
vector=torch.tensor([6,6])

In [5]:
vector

tensor([6, 6])

In [6]:
vector.shape

torch.Size([2])

In [7]:
vector.ndim

1

In [8]:
# MATRIX
MATRIX= torch.tensor([[6,7],
                      [5,4]])

In [9]:
MATRIX

tensor([[6, 7],
        [5, 4]])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX.ndim

2

In [12]:
# tensor
TENSOR =torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])

In [13]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR.ndim

3

In [16]:
# creating random numbers
random_tensor=torch.rand([4,3])

In [17]:
random_tensor


tensor([[0.7643, 0.2689, 0.0305],
        [0.7197, 0.2492, 0.1971],
        [0.5136, 0.6115, 0.4478],
        [0.7385, 0.4799, 0.2170]])

In [18]:
random_tensor.shape

torch.Size([4, 3])

In [19]:
random_tensor.ndim

2

In [20]:
# create a random tensor with similar shape to an image
random_image_size_tensor=torch.rand(size=(224,224,3))

In [21]:
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
torch.rand(size=(3,3))#giving in tuple and metion size

tensor([[0.2735, 0.8334, 0.1627],
        [0.9673, 0.3388, 0.1049],
        [0.1643, 0.4148, 0.0363]])

In [23]:
torch.rand(3,3)# with out mentioning size by defualt it takes size

tensor([[0.0905, 0.7873, 0.7419],
        [0.6268, 0.6855, 0.4687],
        [0.7831, 0.0820, 0.0115]])

zeros and ones

In [24]:
# create tensor with all zeros
zeros=torch.zeros(4,3)

In [25]:
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [26]:
#if we want to convert random tensor to zeros
zeros*random_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [27]:
# create tensor of all ones
ones=torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

In [29]:

### creating a range of tensors and tensors like

# creating a range of tensors and tensors like

In [30]:
torch.__version__

'2.1.0+cu121'

In [31]:
one_to_ten=torch.arange(1,10)

In [32]:
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
one_to_ten=torch.arange(start=1,end=11,step=1)

In [35]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
# creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#  tensor datatypes

In [37]:
float_32_tensor=torch.tensor([3.,6.,9.],
                             dtype=None,
                             device=None,
                             requires_grad=False)

In [38]:
float_32_tensor

tensor([3., 6., 9.])

In [39]:
float_16_tensor=float_32_tensor.type(torch.float16)

In [40]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [41]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [42]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [43]:
int_32_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [44]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [45]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.4706, 0.4119, 0.3079, 0.3981],
        [0.7830, 0.1166, 0.3013, 0.7486],
        [0.6911, 0.5232, 0.4557, 0.1060]])

In [46]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor :{some_tensor.dtype}")
print(f"shape of tensor :{some_tensor.shape}")
print(f"Device of tensor :{some_tensor.device}")

tensor([[0.4706, 0.4119, 0.3079, 0.3981],
        [0.7830, 0.1166, 0.3013, 0.7486],
        [0.6911, 0.5232, 0.4557, 0.1060]])
Datatype of tensor :torch.float32
shape of tensor :torch.Size([3, 4])
Device of tensor :cpu


In [47]:
# manipulating tensors (tensor operations)
tensor=torch.tensor([6,4,2])
tensor+ 10

tensor([16, 14, 12])

# multiply by 10


In [48]:
tensor*10

tensor([60, 40, 20])

# subtract by 10

In [49]:
tensor-10

tensor([-4, -6, -8])

In [50]:
# try out pytorch in-built functions
torch.mul(tensor,10)

tensor([60, 40, 20])

In [51]:
torch.add(tensor,10)

tensor([16, 14, 12])

In [52]:
# element wise multiplucation
print(tensor, "*",tensor)
print(f"equals:{tensor*tensor}")

tensor([6, 4, 2]) * tensor([6, 4, 2])
equals:tensor([36, 16,  4])


In [53]:
# matrix multpication
torch.matmul(tensor,tensor)

tensor(56)

In [54]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(56)
CPU times: user 2.23 ms, sys: 0 ns, total: 2.23 ms
Wall time: 2.29 ms


In [55]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.47 ms, sys: 0 ns, total: 1.47 ms
Wall time: 1.59 ms


tensor(56)

In [56]:
tensor @ tensor

tensor(56)

In [57]:
# matmul
torch.matmul(torch.rand(3,3),torch.rand(3,2))

tensor([[0.7409, 0.9033],
        [0.3639, 0.7581],
        [0.7760, 0.7920]])

In [58]:
tensor_A=torch.tensor([[1,2,8,1],
                      [3,4,5,1],
                      [5,6,7,1]])

In [59]:
tensor_B=torch.tensor([[7,6],
                       [7,4],
                       [8,4]])

In [60]:
tensor_B.shape

torch.Size([3, 2])

In [61]:
tensor_A.shape

torch.Size([3, 4])

In [62]:
tetorch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x2)

In [63]:
tensor_A.T

tensor([[1, 3, 5],
        [2, 4, 6],
        [8, 5, 7],
        [1, 1, 1]])

In [64]:
torch.matmul(tensor_A.T,tensor_B)

tensor([[ 68,  38],
        [ 90,  52],
        [147,  96],
        [ 22,  14]])

In [65]:
print(f"original shapes: tensor_A= {tensor_A.shape},tensor_B= {tensor_B.shape}")
print(f"new shapes:tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape} (same shape as above)")
print(f"multiplying : {tensor_A.T.shape}  @ {tensor_B.shape}  ----->inner dimensions must match")
output=torch.matmul(tensor_A.T ,tensor_B)
print(output)
print(f"output:{output.shape}")

original shapes: tensor_A= torch.Size([3, 4]),tensor_B= torch.Size([3, 2])
new shapes:tensor_A = torch.Size([3, 4]) , tensor_B = torch.Size([3, 2]) (same shape as above)
multiplying : torch.Size([4, 3])  @ torch.Size([3, 2])  ----->inner dimensions must match
tensor([[ 68,  38],
        [ 90,  52],
        [147,  96],
        [ 22,  14]])
output:torch.Size([4, 2])


### finding the min,max,mean,sum etc...


In [66]:
# finding min
x=torch.arange(0,100,5)
x

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [67]:
x.dtype

torch.int64

In [68]:
x.min()

tensor(0)

In [69]:
torch.min(x)

tensor(0)

In [70]:
# finding max
x.max(),torch.max(x)

(tensor(95), tensor(95))

In [71]:
# find the mean note: torch.mean() function requires a tensor of type float32
torch.mean(x.type(torch.float32))

tensor(47.5000)

In [72]:
#find the sum
torch.sum(x),x.sum()

(tensor(950), tensor(950))

# finding positional min and max

In [73]:
# finding positional min and max
torch.argmax(x), x.argmax()

(tensor(19), tensor(19))

In [74]:
x[19]

tensor(95)

In [75]:
torch.argmin(x),x.argmin()

(tensor(0), tensor(0))

In [76]:
x[0]

tensor(0)

In [77]:
y=torch.arange(1,100,10)

In [78]:
y

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [79]:
y.shape

torch.Size([10])

In [80]:
y_reshaped=y.reshape(5,2)
y_reshaped

tensor([[ 1, 11],
        [21, 31],
        [41, 51],
        [61, 71],
        [81, 91]])

In [81]:
y_reshaped=y.reshape(2,5)
y_reshaped

tensor([[ 1, 11, 21, 31, 41],
        [51, 61, 71, 81, 91]])

In [82]:
y_reshaped=y.reshape(1,10)
y_reshaped

tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [83]:
y_reshaped=y.reshape(10,1)
y_reshaped

tensor([[ 1],
        [11],
        [21],
        [31],
        [41],
        [51],
        [61],
        [71],
        [81],
        [91]])

In [84]:
# view
x=y.view(1,10,)
x,x.shape

(tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]]), torch.Size([1, 10]))

In [85]:

x[ : ,0]=100 # the changes are happening in both the original data and veiw
x,y # view is the copy of the data if we make any changes it reflects in the view

(tensor([[100,  11,  21,  31,  41,  51,  61,  71,  81,  91]]),
 tensor([100,  11,  21,  31,  41,  51,  61,  71,  81,  91]))

In [86]:
type(x)

torch.Tensor

In [87]:
x=x.type(torch.float32)

In [88]:
# stacking
y_stack=torch.stack([y,y,y,y,y],dim=0)#hstack
y_stack

tensor([[100,  11,  21,  31,  41,  51,  61,  71,  81,  91],
        [100,  11,  21,  31,  41,  51,  61,  71,  81,  91],
        [100,  11,  21,  31,  41,  51,  61,  71,  81,  91],
        [100,  11,  21,  31,  41,  51,  61,  71,  81,  91],
        [100,  11,  21,  31,  41,  51,  61,  71,  81,  91]])

In [89]:
y_stack=torch.stack([y,y,y,y,y],dim=1)# vstack
y_stack

tensor([[100, 100, 100, 100, 100],
        [ 11,  11,  11,  11,  11],
        [ 21,  21,  21,  21,  21],
        [ 31,  31,  31,  31,  31],
        [ 41,  41,  41,  41,  41],
        [ 51,  51,  51,  51,  51],
        [ 61,  61,  61,  61,  61],
        [ 71,  71,  71,  71,  71],
        [ 81,  81,  81,  81,  81],
        [ 91,  91,  91,  91,  91]])

In [90]:
# squeeze
y_reshaped

tensor([[100],
        [ 11],
        [ 21],
        [ 31],
        [ 41],
        [ 51],
        [ 61],
        [ 71],
        [ 81],
        [ 91]])

In [91]:
y_reshaped.shape

torch.Size([10, 1])

In [92]:
y_squezed=y_reshaped.squeeze(dim=0)

In [93]:
y_squezed  #removes the dimensions

tensor([[100],
        [ 11],
        [ 21],
        [ 31],
        [ 41],
        [ 51],
        [ 61],
        [ 71],
        [ 81],
        [ 91]])

In [94]:
y_squezed.shape

torch.Size([10, 1])

In [95]:
# unsqueeze
y_unsquezed=y_squezed.unsqueeze(dim=0)

In [96]:
y_unsquezed # adds one more dimension

tensor([[[100],
         [ 11],
         [ 21],
         [ 31],
         [ 41],
         [ 51],
         [ 61],
         [ 71],
         [ 81],
         [ 91]]])

In [97]:
y_unsquezed.shape

torch.Size([1, 10, 1])

In [98]:
# permuted
original=torch.rand(3,244,244)

In [99]:
permuted=original.permute(1,2,0)

In [100]:
permuted.shape,original.shape

(torch.Size([244, 244, 3]), torch.Size([3, 244, 244]))

In [101]:
original[2,2,2]=1
original[2,2,2],permuted[2,2,2]

(tensor(1.), tensor(1.))

In [102]:
x=torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [103]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [104]:
x[0][0]

tensor([1, 2, 3])

In [105]:
x[0][0][0]

tensor(1)

# question:find the number 9

In [106]:
x[0][2][2]

tensor(9)

In [107]:
x[:,2,2]

tensor([9])

In [108]:
# get all values of 0 but only the first index value of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [109]:
# get index 0 of oth index and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

# index on x to return 3,6,9

In [110]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [111]:
x[:,:,2]

tensor([[3, 6, 9]])

In [121]:
# numpy to tensor
x =np.arange(1,10)

In [122]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
tensor=torch.from_numpy(x)

In [124]:
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
x.dtype

dtype('int64')

In [126]:
x=x+2

In [127]:
x,tensor # there is no change in tensor

(array([ 3,  4,  5,  6,  7,  8,  9, 10, 11]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [129]:
#  converting tensor to numpy
array = torch.zeros(8)
numpy_tensor=array.numpy()

In [130]:
numpy_tensor

array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [131]:
array=array+2

In [134]:
array,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2., 2.]),
 array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32))

In [135]:
numpy_tensor.dtype

dtype('float32')